### ISSUE TITLE
Got an error while setting it up for my heat pump

### ISSUE THREAD

**Issue by air2** [klejejs/ha-thermia-heat-pump-integration#1]
Hello, I got the following error message when trying to setup the heat pump. I do not have an internal temperature sensor,
so maybe that is a problem:

Logger: homeassistant.components.water_heater
Source: custom_components/thermia/water_heater.py:69 
Integration: Water Heater (documentation, issues) 
First occurred: 14:27:19 (2 occurrences) 
Last logged: 14:27:19

Error adding entities for domain water_heater with platform thermia
Error while setting up thermia platform for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 513, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 184, in capability_attributes
    self.hass, self.min_temp, self.temperature_unit, self.precision
  File "/config/custom_components/thermia/water_heater.py", line 69, in min_temp
    return self.water_heater.heat_min_temperature_value
  File "/usr/local/lib/python3.9/site-packages/ThermiaOnlineAPI/model/HeatPump.py", line 89, in heat_min_temperature_value
    return self.__temperature_state.get("minValue")
AttributeError: 'NoneType' object has no attribute 'get'

This is the json retrieved when for URL: https://online-classic-serviceapi.azurewebsites.net/api/v1/installationstatus/MYID/status  when I use the webinterface:
```
{
    "hasIndoorTempSensor": false,
    "indoorTemperature": 20.000000298023224,
    "isOutdoorTempSensorFunctioning": true,
    "outdoorTemperature": 13,
    "isHotWaterActive": false,
    "hotWaterTemperature": -100,
    "heatingEffect": 20,
    "isHeatingEffectSetByUser": false,
    "heatingEffectRegisters": [
        null,
        1012
    ],
    "reducedHeatingEffect": 19,
    "reducedHeatingEffectRegisters": [
        null,
        1007
    ],
    "isReducedHeatingEffectSetByUser": false,
    "programVersion": "1.2.0",
    "dcmVersion": "2.0.17",
    "linkIntegrationStatus": false,
    "roomFactor": 2,
    "hotWaterRegistryName": "UI_TAP_WATER",
    "isGaugeDifferenciated": false
}
```

**Comment by air2** [comment]
I digged a bit deeper and I think this is the response which is processed:
URL: https://online-classic-serviceapi.azurewebsites.net/api/v1/Registers/Installations/MYID/Groups/REG_GROUP_TEMPERATURES



```
[{
    "registerId": 10001,
    "registerIndex": 2010,
    "registerName": "REG_OPER_DATA_OUTDOOR_TEMP_MA_SA",
    "registerValue": 13,
    "stringRegisterValue": null,
    "timeStamp": "2021-12-30T11:05:00.671Z",
    "isComputedRegister": false,
    "presentation": "Integer",
    "isReadOnly": true,
    "minValue": null,
    "maxValue": null,
    "valueNames": null,
    "falseText": null,
    "trueText": null,
    "step": 1,
    "modifier": 8,
    "disabledByLink": false,
    "isInvisible": false,
    "canBeShownInGraph": true,
    "graphRegisterIndex": 10001,
    "canBeShownInHistory": true,
    "collapsible": false,
    "order": 70105
}, {
    "registerId": 10007,
    "registerIndex": 2060,
    "registerName": "REG_INDOOR_TEMPERATURE",
    "registerValue": 20,
    "stringRegisterValue": null,
    "timeStamp": "2021-03-10T09:01:51.24Z",
    "isComputedRegister": false,
    "presentation": "Integer",
    "isReadOnly": true,
    "minValue": null,
    "maxValue": null,
    "valueNames": null,
    "falseText": null,
    "trueText": null,
    "step": 0.10000000149011612,
    "modifier": 8,
    "disabledByLink": false,
    "isInvisible": false,
    "canBeShownInGraph": true,
    "graphRegisterIndex": 10007,
    "canBeShownInHistory": true,
    "collapsible": false,
    "order": 70135
}, {
    "registerId": 10008,
    "registerIndex": 2000,
    "registerName": "REG_OPER_DATA_SUPPLY_MA_SA",
    "registerValue": 29,
    "stringRegisterValue": null,
    "timeStamp": "2021-12-30T15:41:36.777Z",
    "isComputedRegister": false,
    "presentation": "Integer",
    "isReadOnly": true,
    "minValue": null,
    "maxValue": null,
    "valueNames": null,
    "falseText": null,
    "trueText": null,
    "step": 1,
    "modifier": 12,
    "disabledByLink": false,
    "isInvisible": false,
    "canBeShownInGraph": true,
    "graphRegisterIndex": 10008,
    "canBeShownInHistory": true,
    "collapsible": false,
    "order": 70145
}, {
    "registerId": 10015,
    "registerIndex": 2007,
    "registerName": "REG_OPER_DATA_SYS_SUPPLY",
    "registerValue": 28,
    "stringRegisterValue": null,
    "timeStamp": "2021-12-30T15:22:15.314Z",
    "isComputedRegister": false,
    "presentation": "Integer",
    "isReadOnly": true,
    "minValue": null,
    "maxValue": null,
    "valueNames": null,
    "falseText": null,
    "trueText": null,
    "step": 1,
    "modifier": 8,
    "disabledByLink": false,
    "isInvisible": false,
    "canBeShownInGraph": true,
    "graphRegisterIndex": 10015,
    "canBeShownInHistory": true,
    "collapsible": false,
    "order": 70175
}, {
    "registerId": 10016,
    "registerIndex": 2122,
    "registerName": "REG_DESIRED_SYS_SUPPLY_LINE_TEMP",
    "registerValue": 0,
    "stringRegisterValue": null,
    "timeStamp": "2021-10-11T09:30:11.967Z",
    "isComputedRegister": false,
    "presentation": "Integer",
    "isReadOnly": true,
    "minValue": null,
    "maxValue": null,
    "valueNames": null,
    "falseText": null,
    "trueText": null,
    "step": 1,
    "modifier": 8,
    "disabledByLink": false,
    "isInvisible": false,
    "canBeShownInGraph": true,
    "graphRegisterIndex": 10016,
    "canBeShownInHistory": true,
    "collapsible": false,
    "order": 70180
}]
```

**Comment by klejejs** [comment]
Thank you for the detailed response, it helps a lot!

To me it looks like different heat pumps have different `registerIndex` values which is why the integration breaks for you. 

Could you please check what request is sent when you change temperature and operation mode in online website?
To me requests are made to to https://online-classic-serviceapi.azurewebsites.net/api/v1/Registers/Installations/MYID/Registers with payloads:
`{registerIndex: 50, registerValue: 20(target), clientUuid: "some-random-id-that-does-not-matter"}` for temperature
and `{registerIndex: 51, registerValue: 0(target), clientUuid: "some-random-id-that-does-not-matter"}` for operation mode.
I would assume the requests are same for you, but the `registerIndex` values are different, am I right? What are the values for you?
Also, could you please provide a model for your heat pump, so I can make a list of heat pumps that work?

**Comment by air2** [comment]
For the operation mode it is:
{"registerIndex":1363,"registerValue":0,"clientUuid":"uuid"}

**Comment by air2** [comment]
For the temp it is
{"registerIndex":1012,"registerValue":19,"clientUuid":"uuid"}

**Comment by klejejs** [comment]
Thank you! I just released an update to the integration. Could you please check if it works?

**Comment by air2** [comment]
Yeah but that will not be today i guess. I hope tomorrow. Thank u for the fast response

**Comment by air2** [comment]
Got some time to test it: now i get 

Logger: ThermiaOnlineAPI.api.ThermiaAPI
Source: /usr/local/lib/python3.9/site-packages/ThermiaOnlineAPI/api/ThermiaAPI.py:82 
First occurred: 19:16:53 (1 occurrences) 
Last logged: 19:16:53

Error in getting device's temperature status. Could not find temperature by register.

but i get the water heater entity

**Comment by klejejs** [comment]
Ok. And besides the error, does the entity work? Can you change temperature and operation from Home Assistant?

**Comment by air2** [comment]
Yeah it works!

is it also possible to add the outside temperature as sensor? Would be nice to see a history of the outside temperature compared to the heat demand and energy usage.

**Comment by air2** [comment]
Compressor on off is also working

**Comment by klejejs** [comment]
Good to know. I will remove the error logs and look into adding the outside temperature sensor.
Thanks for your help in figuring this out!
