### ISSUE TITLE
Include sensor for PID

### ISSUE THREAD

**Issue by oskari** [klejejs/ha-thermia-heat-pump-integration#107]
Would be great if we could bring the PID value to HA. While it might not be too useful for any automation, I would like to see the history of that value at least.

**Comment by klejejs** [comment]
The latest release adds the sensor. In case it is not available for your heat pump, please create a new issue and attach your heat pump debug data as described [here](https://github.com/klejejs/ha-thermia-heat-pump-integration?tab=readme-ov-file#adding-support-for-new-heat-pump-models), so I can investigate it further.
