### ISSUE TITLE
Feature request: Sensor data similar to thermia app

### ISSUE THREAD

**Issue by nisarerbest** [klejejs/ha-thermia-heat-pump-integration#11]
Hey,

The integration is working well on Genesis API. Sensor data (Temperatures) is the key request. Similar to the app (as I dont want to use the Thermia app).

Keep up the awesome work :)

![Screenshot_20220119-215345](https://user-images.githubusercontent.com/21986237/150212414-87da4741-1291-4fe6-90d5-1559681c909e.jpg)

![Screenshot_20220119-215400](https://user-images.githubusercontent.com/21986237/150212590-ee33c96e-2817-42b4-a5b4-583e36b79869.jpg)

**Comment by klejejs** [comment]
Thanks for the suggestion! I will look into it.

**Comment by klejejs** [comment]
Just released an update with a bunch of new sensors.
Feel free to check it out and report back with any bugs/comments/suggestions.

**Comment by nisarerbest** [comment]
I've tried the new sensor data for about a day. Working super well :)

**Comment by andeny** [comment]
i have tried this integration for a couple of days now and it looks great. i have one problem with the values not being updated in homeassistant. i have to manualy reload the integration or restart homeassistant to get the new values. it seems it only get them ones every restart/reload. have i missed something ?
i have activated pull in homeassistant

**Comment by andeny** [comment]
actually found this in the loggs if it helps
Error fetching thermia data: HTTPSConnectionPool(host='online-genesis-serviceapi.azurewebsites.net', port=443): Max retries exceeded with url: /api/v1/Registers/Installations/1533268/Groups/REG_GROUP_HOT_WATER (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f947b51d310>: Failed to establish a new connection: [Errno 110] Operation timed out'))

**Comment by klejejs** [comment]
@andeny Thanks for reporting this. I'll check it out.
I will, however, create a new issue for this as this is unrelated to the sensors' request.

**Comment by nisarerbest** [comment]
> i have tried this integration for a couple of days now and it looks great. i have one problem with the values not being updated in homeassistant. i have to manualy reload the integration or restart homeassistant to get the new values. it seems it only get them ones every restart/reload. have i missed something ? i have activated pull in homeassistant
> 
> @klejejs

Hi, I'm also experiencing the same issue. Data is updated once upon reload.

**Comment by klejejs** [comment]
@andeny Do you also have Genesis type heat pump? I wonder if the issue is related to that.
