### ISSUE TITLE
Network timeout issues

### ISSUE THREAD

**Issue by klejejs** [klejejs/ha-thermia-heat-pump-integration#13]
@andeny Mentioned:
> i have tried this integration for a couple of days now and it looks great. i have one problem with the values not being updated in homeassistant. i have to manualy reload the integration or restart homeassistant to get the new values. it seems it only get them ones every restart/reload. have i missed something ?
i have activated pull in homeassistant

> actually found this in the loggs if it helps
Error fetching thermia data: HTTPSConnectionPool(host='online-genesis-serviceapi.azurewebsites.net', port=443): Max retries exceeded with url: /api/v1/Registers/Installations/1533268/Groups/REG_GROUP_HOT_WATER (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f947b51d310>: Failed to establish a new connection: [Errno 110] Operation timed out'))

**Comment by andeny** [comment]
@klejejs yes, i have the genesis platform on my pump. It's the Atlas 12 heatpump.

**Comment by frealv** [comment]
I Also having this problem - Atlas 18 heat pump(genesis)

**Comment by nisarerbest** [comment]
Hi. The sensors are updating only during first time installation. Sensors aren't updated until a reload is performed

**Comment by toolonghere** [comment]
Hi, 
I have the exact same problem, that I get to no updates. But I don't have the same logg entry @andeny described.

**Comment by klejejs** [comment]
Hello @nisarerbest, @toolonghere, @danialclements!

Thanks for also reporting the issue.
Can I just confirm that all of you have set the `genesis` API type during the setup of the integration?

If this is the case, it seems API for genesis heat pumps is a bit different after all, and I will have to figure out the issue without having access to a real device.

**Comment by klejejs** [comment]
Also, could you please confirm whether the issue is only for sensors, or also for hot water switch, operation temperature, and operation mode too?

**Comment by nisarerbest** [comment]
> Hello @nisarerbest, @toolonghere, @danialclements!
> 
> Thanks for also reporting the issue. Can I just confirm that all of you have set the `genesis` API type during the setup of the integration?
> 
> If this is the case, it seems API for genesis heat pumps is a bit different after all, and I will have to figure out the issue without having access to a real device.

Hi @klejejs ,

Yes. Using the genesis API (Atlas 12).

I won't be able to test the hot water switch. If i screw up and hot water switches off, my wife will kill me, and i won't be able to report any bugs :)

**Comment by danialclements** [comment]
Yes, I'm on genesis too.  I've got a Calibra 12.  I had changed the operation temperature yesterday using the home assistant UI which did update the heat pump correctly.  I've also updated the temperature directly on the unit and see the change reflected in Home Assistant without having to reload the integration so I'm thinking its just the sensors.  I might be able to do some debugging this weekend if needed so let me know if there is something to check or tweak.

**Comment by toolonghere** [comment]
Hi, I have a Diplomat, and I'm running Classic. It only updates when reloaded, and the operation switch does not update the pump when I change the value in the interface.

**Comment by klejejs** [comment]
Ok, thanks for the reports! That means it is not related to `genesis` type. I'll try to understand what the core issue is.

**Comment by klejejs** [comment]
Could any of you please try some debugging for me?

It would be very useful if you could login to your heat pump online through Thermia website, open browser "Developer tools" -> "Network tab", find requests with URLs `https://online...serviceapi.azurewebsites.net/api/v1/installations/{your_id}`, `https://online...serviceapi.azurewebsites.net/api/v1/installationstatus/{your_id}/status` and `https://online...serviceapi.azurewebsites.net/api/v1/Registers/Installations/{your_id}/Groups/REG_GROUP_TEMPERATURES`and paste response data here. This would allow me to compare how the data is different to what I see and thus it might help me figuring out the issue. Just please don't forget to remove any sensitive data!

I'd really appreciate your help!

**Comment by andeny** [comment]
{change temp +}
Request URL: https://online-genesis-serviceapi.azurewebsites.net/api/v1/Registers/Installations/[7numbers]/Groups/REG_GROUP_COOLING
Request Method: OPTIONS
Status Code: 204 
Remote Address: [Not sure abot this number]
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-credentials: true
access-control-allow-headers: authorization,cache-control,pragma
access-control-allow-methods: GET
access-control-allow-origin: https://online-genesis.thermia.se
date: Sun, 13 Feb 2022 15:07:47 GMT
request-context: appId=cid-v1:XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX
server: Microsoft-IIS/10.0
vary: Origin
x-powered-by: ASP.NET
:authority: online-genesis-serviceapi.azurewebsites.net
:method: OPTIONS
:path: /api/v1/Registers/Installations/(7 numbers)/Groups/REG_GROUP_COOLING
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: sv,en;q=0.9,en-GB;q=0.8,en-US;q=0.7
access-control-request-headers: authorization,cache-control,pragma
access-control-request-method: GET
origin: https://online-genesis.thermia.se
referer: https://online-genesis.thermia.se/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.50

**Comment by andeny** [comment]
Request URL: https://online-genesis-serviceapi.azurewebsites.net/api/v1/Registers/Installations/[my-id]/Groups/REG_GROUP_TEMPERATURES
Request Method: OPTIONS
Status Code: 204 
Remote Address: XX.XX:XX.XXX:443
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-credentials: true
access-control-allow-headers: authorization,cache-control,pragma
access-control-allow-methods: GET
access-control-allow-origin: https://online-genesis.thermia.se
date: Sun, 13 Feb 2022 15:12:59 GMT
request-context: appId=cid-v1:XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX
server: Microsoft-IIS/10.0
vary: Origin
x-powered-by: ASP.NET
:authority: online-genesis-serviceapi.azurewebsites.net
:method: OPTIONS
:path: /api/v1/Registers/Installations/[my-id]/Groups/REG_GROUP_TEMPERATURES
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: sv,en;q=0.9,en-GB;q=0.8,en-US;q=0.7
access-control-request-headers: authorization,cache-control,pragma
access-control-request-method: GET
origin: https://online-genesis.thermia.se
referer: https://online-genesis.thermia.se/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.50

**Comment by andeny** [comment]
Request URL: https://online-genesis-serviceapi.azurewebsites.net/api/v1/installation/[my-id]/events/status
Request Method: OPTIONS
Status Code: 204 
Remote Address: xx.xx.xx.xxx:443
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-credentials: true
access-control-allow-headers: authorization,cache-control,pragma
access-control-allow-methods: GET
access-control-allow-origin: https://online-genesis.thermia.se
date: Sun, 13 Feb 2022 15:31:02 GMT
request-context: appId=cid-v1:XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX
server: Microsoft-IIS/10.0
vary: Origin
x-powered-by: ASP.NET
:authority: online-genesis-serviceapi.azurewebsites.net
:method: OPTIONS
:path: /api/v1/installation/[my-id]/events/status
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: sv,en;q=0.9,en-GB;q=0.8,en-US;q=0.7
access-control-request-headers: authorization,cache-control,pragma
access-control-request-method: GET
origin: https://online-genesis.thermia.se
referer: https://online-genesis.thermia.se/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.50

**Comment by nisarerbest** [comment]
`Request URL: https://online-genesis-serviceapi.azurewebsites.net/api/v1/installations/xxxxx
Request Method: OPTIONS
Status Code: 204 
Remote Address: xx.xxx.xx.xxx:443
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-credentials: true
access-control-allow-headers: authorization,cache-control,pragma
access-control-allow-methods: GET
access-control-allow-origin: https://www.online-genesis.thermia.se
date: Sun, 13 Feb 2022 17:49:03 GMT
request-context: appId=cid-v1:7b5ae7fd-xxxx-xxx-xxxx-xxxxxxxxxxxx
server: Microsoft-IIS/10.0
vary: Origin
x-powered-by: ASP.NET
:authority: online-genesis-serviceapi.azurewebsites.net
:method: OPTIONS
:path: /api/v1/installations/xxxxxxx
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-NO,en;q=0.9,nb-NO;q=0.8,nb;q=0.7,en-US;q=0.6
access-control-request-headers: authorization,cache-control,pragma
access-control-request-method: GET
origin: https://www.online-genesis.thermia.se
referer: https://www.online-genesis.thermia.se/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (X11; CrOS x86_64 13729.56.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.95 Safari/537.36`

**Comment by nisarerbest** [comment]
get:
`Request URL: https://online-genesis-serviceapi.azurewebsites.net/api/v1/installations/xxxxxxx
Request Method: GET
Status Code: 200 
Remote Address: xx.xxx.xx.xxx:443
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-credentials: true
access-control-allow-origin: https://www.online-genesis.thermia.se
api-supported-versions: 1.0
content-encoding: gzip
content-length: 519
content-type: application/json; charset=utf-8
date: Sun, 13 Feb 2022 17:49:03 GMT
request-context: appId=cid-v1:xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
server: Microsoft-IIS/10.0
vary: Origin,Accept-Encoding
x-frame-options: SAMEORIGIN
x-powered-by: ASP.NET
:authority: online-genesis-serviceapi.azurewebsites.net
:method: GET
:path: /api/v1/installations/xxxxxxx
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-NO,en;q=0.9,nb-NO;q=0.8,nb;q=0.7,en-US;q=0.6
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkJhc2hpciIsIlVzZXJOYW1lIjoibmlzYXIuYmFzaGlyQGdtYWlsLmNvbSIsIkN1bHR1cmUiOiJlbi1VUyIsIlRpbWVab25lIjoiVy4gRXVyb3BlIFN0YW5kYXJkIFRpbWUiLCJJbnZpdGVJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIsIlNlc3Npb25UaW1lb3V0IjoiNjA0ODAwIiwiUmV0YWlsZXJzIjoiW10iLCJleHAiOjE2NDUzNzkzNDEsImlzcyI6InRoZXJtaWEtYXV0aC1hcGkuYXp1cmV3ZWJzaXRlcy5uZXQvand0IiwiYXVkIjoidGhlcm1pYS1hdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
cache-control: no-cache
dnt: 1
origin: https://www.online-genesis.thermia.se
pragma: no-cache
referer: https://www.online-genesis.thermia.se/
sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (X11; CrOS x86_64 13729.56.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.95 Safari/537.36`

**Comment by nisarerbest** [comment]
`Request URL: https://online-genesis-serviceapi.azurewebsites.net/api/v1/Registers/Installations/xxxxxxx/Groups/REG_GROUP_TEMPERATURES
Request Method: OPTIONS
Status Code: 204 
Remote Address: 5x.xxx.xx.xxx:443
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-credentials: true
access-control-allow-headers: authorization,cache-control,pragma
access-control-allow-methods: GET
access-control-allow-origin: https://www.online-genesis.thermia.se
date: Sun, 13 Feb 2022 17:49:03 GMT
request-context: appId=cid-v1:7xxxxx-x-xxxx-xc
server: Microsoft-IIS/10.0
vary: Origin
x-powered-by: ASP.NET
:authority: online-genesis-serviceapi.azurewebsites.net
:method: OPTIONS
:path: /api/v1/Registers/Installations/xxxxxxx/Groups/REG_GROUP_TEMPERATURES
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-NO,en;q=0.9,nb-NO;q=0.8,nb;q=0.7,en-US;q=0.6
access-control-request-headers: authorization,cache-control,pragma
access-control-request-method: GET
origin: https://www.online-genesis.thermia.se
referer: https://www.online-genesis.thermia.se/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (X11; CrOS x86_64 13729.56.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.95 Safari/537.36`

**Comment by nisarerbest** [comment]
`Request URL: https://online-genesis-serviceapi.azurewebsites.net/api/v1/Registers/Installations/xxxxxxx/Groups/REG_GROUP_TEMPERATURES
Request Method: GET
Status Code: 200 
Remote Address: xx.xxx.xx.xxx:443
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-credentials: true
access-control-allow-origin: https://www.online-genesis.thermia.se
api-supported-versions: 1.0
content-encoding: gzip
content-length: 821
content-type: application/json; charset=utf-8
date: Sun, 13 Feb 2022 17:49:03 GMT
request-context: appId=cid-v1:xxxx-x-xx-x-x-x-x-x
server: Microsoft-IIS/10.0
vary: Origin,Accept-Encoding
x-frame-options: SAMEORIGIN
x-powered-by: ASP.NET
:authority: online-genesis-serviceapi.azurewebsites.net
:method: GET
:path: /api/v1/Registers/Installations/xxxxxxx/Groups/REG_GROUP_TEMPERATURES
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-NO,en;q=0.9,nb-NO;q=0.8,nb;q=0.7,en-US;q=0.6
authorization: Bearer eyJhbGciOiJIUxxxxxxxxxxdGVzLm5ldC9qd3QifQ.umvrTvoL0dmgEeTpXSZwpgxLyemHikBIMaHFpn4I4sw
cache-control: no-cache
dnt: 1
origin: https://www.online-genesis.thermia.se
pragma: no-cache
referer: https://www.online-genesis.thermia.se/
sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (X11; CrOS x86_64 13729.56.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.95 Safari/537.36`

**Comment by nisarerbest** [comment]
there you go @klejejs. Thanks for your contribution buddy!

**Comment by klejejs** [comment]
@andeny @nisarerbest Thanks very much for the pastes, but what you have added is request data, what I really wanted was the response data that includes device info and temperature states (it is in response tab of the request). I'd really appreciate if you could add that too, it would really help.
And thanks in advance! ;)

**Comment by nisarerbest** [comment]
`{"hasIndoorTempSensor":false,"indoorTemperature":200,"isOutdoorTempSensorFunctioning":true,"outdoorTemperature":6,"isHotWaterActive":true,"hotWaterTemperature":60,"heatingEffect":28,"isHeatingEffectSetByUser":false,"heatingEffectRegisters":[null,3],"reducedHeatingEffect":null,"reducedHeatingEffectRegisters":[null,null],"isReducedHeatingEffectSetByUser":null,"programVersion":"10.3.0","dcmVersion":null,"linkIntegrationStatus":false,"roomFactor":3,"hotWaterRegistryName":"UI_TAP_WATER","isGaugeDifferenciated":false}`

**Comment by nisarerbest** [comment]
`[{"registerId":30829,"registerIndex":2000,"registerName":"REG_OUTDOOR_TEMPERATURE","registerValue":6,"stringRegisterValue":null,"timeStamp":"2022-02-13T19:10:31.518Z","isComputedRegister":false,"presentation":"Integer","isReadOnly":true,"minValue":-50,"maxValue":150,"valueNames":null,"falseText":null,"trueText":null,"step":1,"modifier":8,"disabledByLink":false,"isInvisible":false,"canBeShownInGraph":true,"graphRegisterIndex":30829,"canBeShownInHistory":true,"collapsible":false,"order":11003},{"registerId":30810,"registerIndex":5,"registerName":"REG_SUPPLY_LINE","registerValue":41,"stringRegisterValue":null,"timeStamp":"2022-02-13T19:55:33.317Z","isComputedRegister":false,"presentation":"Integer","isReadOnly":true,"minValue":null,"maxValue":null,"valueNames":null,"falseText":null,"trueText":null,"step":1,"modifier":12,"disabledByLink":false,"isInvisible":false,"canBeShownInGraph":true,"graphRegisterIndex":30810,"canBeShownInHistory":true,"collapsible":false,"order":11004},{"registerId":30830,"registerIndex":2002,"registerName":"REG_OPER_DATA_RETURN","registerValue":38,"stringRegisterValue":null,"timeStamp":"2022-02-13T19:54:33.318Z","isComputedRegister":false,"presentation":"Integer","isReadOnly":true,"minValue":-50,"maxValue":150,"valueNames":null,"falseText":null,"trueText":null,"step":1,"modifier":12,"disabledByLink":false,"isInvisible":false,"canBeShownInGraph":true,"graphRegisterIndex":30830,"canBeShownInHistory":true,"collapsible":false,"order":11005},{"registerId":30812,"registerIndex":9,"registerName":"REG_BRINE_IN","registerValue":7,"stringRegisterValue":null,"timeStamp":"2022-02-13T19:40:31.508Z","isComputedRegister":false,"presentation":"Integer","isReadOnly":true,"minValue":-50,"maxValue":150,"valueNames":null,"falseText":null,"trueText":null,"step":1,"modifier":12,"disabledByLink":false,"isInvisible":false,"canBeShownInGraph":true,"graphRegisterIndex":30812,"canBeShownInHistory":true,"collapsible":false,"order":11009},{"registerId":30811,"registerIndex":8,"registerName":"REG_BRINE_OUT","registerValue":3,"stringRegisterValue":null,"timeStamp":"2022-02-13T19:51:33.324Z","isComputedRegister":false,"presentation":"Integer","isReadOnly":true,"minValue":-50,"maxValue":150,"valueNames":null,"falseText":null,"trueText":null,"step":1,"modifier":12,"disabledByLink":false,"isInvisible":false,"canBeShownInGraph":true,"graphRegisterIndex":30811,"canBeShownInHistory":true,"collapsible":false,"order":11010},{"registerId":30831,"registerIndex":2003,"registerName":"REG_HOT_WATER_TEMPERATURE","registerValue":60,"stringRegisterValue":null,"timeStamp":"2022-02-13T18:36:33.344Z","isComputedRegister":false,"presentation":"Integer","isReadOnly":true,"minValue":-50,"maxValue":150,"valueNames":null,"falseText":null,"trueText":null,"step":1,"modifier":8,"disabledByLink":false,"isInvisible":false,"canBeShownInGraph":true,"graphRegisterIndex":30831,"canBeShownInHistory":true,"collapsible":false,"order":11016},{"registerId":30837,"registerIndex":2122,"registerName":"REG_DESIRED_SYS_SUPPLY_LINE_TEMP","registerValue":42,"stringRegisterValue":null,"timeStamp":"2022-02-13T16:40:31.556Z","isComputedRegister":false,"presentation":"Integer","isReadOnly":true,"minValue":null,"maxValue":null,"valueNames":null,"falseText":null,"trueText":null,"step":1,"modifier":8,"disabledByLink":false,"isInvisible":false,"canBeShownInGraph":true,"graphRegisterIndex":30837,"canBeShownInHistory":true,"collapsible":false,"order":11024}]`

**Comment by nisarerbest** [comment]
I hope I pasted the correct data @klejejs

**Comment by andeny** [comment]
Request URL: https://online-genesis-serviceapi.azurewebsites.net/api/v1/installationstatus/[my-id]/status
Answer:
{"hasIndoorTempSensor":true,"indoorTemperature":21,"isOutdoorTempSensorFunctioning":true,"outdoorTemperature":3,"isHotWaterActive":true,"hotWaterTemperature":61,"heatingEffect":23,"isHeatingEffectSetByUser":false,"heatingEffectRegisters":[null,3],"reducedHeatingEffect":null,"reducedHeatingEffectRegisters":[null,null],"isReducedHeatingEffectSetByUser":null,"programVersion":"10.2.15","dcmVersion":null,"linkIntegrationStatus":false,"roomFactor":2,"hotWaterRegistryName":"UI_TAP_WATER","isGaugeDifferenciated":false}

**Comment by andeny** [comment]
Temp Answer:

[{"registerId":30835,"registerIndex":2060,"registerName":"REG_INDOOR_TEMPERATURE","registerValue":21,"stringRegisterValue":null,"timeStamp":"2022-02-13T20:15:24.123Z","isComputedRegister":false,"presentation":"Integer","isReadOnly":true,"minValue":null,"maxValue":null,"valueNames":null,"falseText":null,"trueText":null,"step":1,"modifier":8,"disabledByLink":false,"isInvisible":false,"canBeShownInGraph":true,"graphRegisterIndex":30835,"canBeShownInHistory":true,"collapsible":false,"order":11002},{"registerId":30829,"registerIndex":2000,"registerName":"REG_OUTDOOR_TEMPERATURE","registerValue":2,"stringRegisterValue":null,"timeStamp":"2022-02-13T21:36:05.184Z","isComputedRegister":false,"presentation":"Integer","isReadOnly":true,"minValue":-50,"maxValue":150,"valueNames":null,"falseText":null,"trueText":null,"step":1,"modifier":8,"disabledByLink":false,"isInvisible":false,"canBeShownInGraph":true,"graphRegisterIndex":30829,"canBeShownInHistory":true,"collapsible":false,"order":11003},{"registerId":30810,"registerIndex":5,"registerName":"REG_SUPPLY_LINE","registerValue":48,"stringRegisterValue":null,"timeStamp":"2022-02-13T21:41:05.184Z","isComputedRegister":false,"presentation":"Integer","isReadOnly":true,"minValue":null,"maxValue":null,"valueNames":null,"falseText":null,"trueText":null,"step":1,"modifier":12,"disabledByLink":false,"isInvisible":false,"canBeShownInGraph":true,"graphRegisterIndex":30810,"canBeShownInHistory":true,"collapsible":false,"order":11004},{"registerId":30830,"registerIndex":2002,"registerName":"REG_OPER_DATA_RETURN","registerValue":45,"stringRegisterValue":null,"timeStamp":"2022-02-13T21:41:05.184Z","isComputedRegister":false,"presentation":"Integer","isReadOnly":true,"minValue":-50,"maxValue":150,"valueNames":null,"falseText":null,"trueText":null,"step":1,"modifier":12,"disabledByLink":false,"isInvisible":false,"canBeShownInGraph":true,"graphRegisterIndex":30830,"canBeShownInHistory":true,"collapsible":false,"order":11005},{"registerId":30812,"registerIndex":9,"registerName":"REG_BRINE_IN","registerValue":-1,"stringRegisterValue":null,"timeStamp":"2022-02-13T15:48:35.152Z","isComputedRegister":false,"presentation":"Integer","isReadOnly":true,"minValue":-50,"maxValue":150,"valueNames":null,"falseText":null,"trueText":null,"step":1,"modifier":12,"disabledByLink":false,"isInvisible":false,"canBeShownInGraph":true,"graphRegisterIndex":30812,"canBeShownInHistory":true,"collapsible":false,"order":11009},{"registerId":30811,"registerIndex":8,"registerName":"REG_BRINE_OUT","registerValue":-5,"stringRegisterValue":null,"timeStamp":"2022-02-13T20:44:05.203Z","isComputedRegister":false,"presentation":"Integer","isReadOnly":true,"minValue":-50,"maxValue":150,"valueNames":null,"falseText":null,"trueText":null,"step":1,"modifier":12,"disabledByLink":false,"isInvisible":false,"canBeShownInGraph":true,"graphRegisterIndex":30811,"canBeShownInHistory":true,"collapsible":false,"order":11010},{"registerId":30831,"registerIndex":2003,"registerName":"REG_HOT_WATER_TEMPERATURE","registerValue":61,"stringRegisterValue":null,"timeStamp":"2022-02-13T21:18:35.041Z","isComputedRegister":false,"presentation":"Integer","isReadOnly":true,"minValue":-50,"maxValue":150,"valueNames":null,"falseText":null,"trueText":null,"step":1,"modifier":8,"disabledByLink":false,"isInvisible":false,"canBeShownInGraph":true,"graphRegisterIndex":30831,"canBeShownInHistory":true,"collapsible":false,"order":11016},{"registerId":30837,"registerIndex":2122,"registerName":"REG_DESIRED_SYS_SUPPLY_LINE_TEMP","registerValue":39,"stringRegisterValue":null,"timeStamp":"2022-02-13T21:40:05.185Z","isComputedRegister":false,"presentation":"Integer","isReadOnly":true,"minValue":null,"maxValue":null,"valueNames":null,"falseText":null,"trueText":null,"step":1,"modifier":8,"disabledByLink":false,"isInvisible":false,"canBeShownInGraph":true,"graphRegisterIndex":30837,"canBeShownInHistory":true,"collapsible":false,"order":11024}]

**Comment by andeny** [comment]
{"deviceId":1xxxxx9,"macAddress":"[device mac]","hasUserAccount":true,"isOnline":true,"lastOnline":"2022-02-13T21:46:05.23","createdWhen":"2021-03-18T15:21:28.994","retailerAccess":10,"ownerId":null,"id":{device-id},"name":"[my-name]","address":{"addressLine1":"[my-adress]","addressLine2":"","zip":"","city":"[my-city]"},"model":"Atlas 12","operationManualUrl":"https://thermia.com/products/thermia-online/","timeZoneId":"W. Europe Standard Time","retailerId":"[retail-id]","hasLinkUnit":false,"installationProfileId":1024}

**Comment by andeny** [comment]
@klejejs one thing i noticed is that i don't always have a response. developer tools: "failed to load response: no content avialible for preflight request"
just noticed it and maybe it's to some help

**Comment by klejejs** [comment]
I have released version 2.8 that refactors the component and should fix the issue. I have high hopes for that.
Please test and report back.

**Note:** As mentioned in release notes, unfortunately, I had previously made a mistake in config flow, so after updating to the latest version, you will see empty duplicate devices of your heat pumps and the only way to remove them is by deleting the integration and adding it once again. I am sorry for the inconvenience. 😞

**Comment by andeny** [comment]
thanks, i have tested for an hour now and it looks to update now. will let you know tonight how it goes :)

**Comment by nisarerbest** [comment]
Thanks @klejejs . Will also provide feedback later tonight.

**Comment by andeny** [comment]
@klejejs it works really well as I can see. Updates quick now so I can follow every value Great work 🙂 you can actually se exactly when I updated to 2.8
![Screenshot_20220215-223844_Home Assistant](https://user-images.githubusercontent.com/60667217/154154849-1d3f872f-7553-4aaf-913c-31236fa63842.jpg)

**Comment by danialclements** [comment]
@klejejs Confirmed the update is working for me as well.  Thanks for getting this fixed, great work!

**Comment by klejejs** [comment]
Great!
Closing the issue as the problem seems to have been fixed. Feel free to open another issue if any problems appear.
