### ISSUE TITLE
Error loading sensor

### ISSUE THREAD

**Issue by andeny** [klejejs/ha-thermia-heat-pump-integration#14]
i updated my homeassistant to latest and got this error

Logger: homeassistant.components.sensor
Source: helpers/entity.py:220
Integration: Sensor (documentation, issues)
First occurred: 09:21:01 (4 occurrences)
Last logged: 09:22:37

Error adding entities for domain sensor with platform thermia
Error while setting up thermia platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 401, in async_get_or_create
    entity_category=_convert_to_entity_category(entity_category),
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 103, in _convert_to_entity_category
    return convert_to_entity_category(value, raise_report=raise_report)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 220, in convert_to_entity_category
    return EntityCategory(value)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'sensor' is not a valid EntityCategory

I think it is connected to a change in home assistant handling sensors and i also get this error:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:74
First occurred: 09:21:01 (16 occurrences)
Last logged: 09:22:37

Detected code that uses str (sensor) for entity category. This is deprecated and will stop working in Home Assistant 2022.4, it should be updated to use EntityCategory instead. Please report this issue.

can you help with this ?
it does not load the temp sensors any moore, see attached picture
![thermia](https://user-images.githubusercontent.com/60667217/152521726-4188f29d-fe48-4be1-9f02-84bf6aa07115.png)

@klejejs

**Comment by klejejs** [comment]
I have released a new version that fixes the problem.
In case you have an issue of HA not starting, please delete `thermia` folder from `config/custom_components` directory and also please edit `config/.storage/core.entity_registry` file and delete all objects that include `"device_class": "sensor"` to make sure that the issue does not appear again.
After doing this and restarting Home Assistant, you should be able to redownload the integration from HACS and everything will be working. No need to re-add heat pumps.
Sorry for the inconvenience :(.

**Comment by andeny** [comment]
Thanks, great work. Now it shows up as before🙂

**Comment by klejejs** [comment]
Actually kudos to @danialclements, he fixed the issue.
