### ISSUE TITLE
Some sensors are not showing up

### ISSUE THREAD

**Issue by klejejs** [klejejs/ha-thermia-heat-pump-integration#24]
@jwictor81 You mentioned that only the following sensors are shown:
* heat_target_temperature
* hot_water_temperature
* outdoor_temperature
* supply_line_temperature

Are you using `classic` or `genesis` API? It could be that they are hidden because they have different values that have not been supported yet.

**Comment by jwictor81** [comment]
Using classic with a Danfoss dhp-aq.

**Comment by jwictor81** [comment]
These are the temp sensors shown in web UI. Is it possible to have them in the integration?
![image](https://user-images.githubusercontent.com/76131121/162723665-3b707639-9adc-403f-bae2-7cf3d3e84fa5.png)

**Comment by Mi3czy** [comment]
@klejejs did you know a lot more control and data is available trough modbus (local connection?)
Any future plans to add this
[Modbus protocol for Genesis platform 10.pdf](https://github.com/klejejs/ha-thermia-heat-pump-integration/files/8592468/Modbus.protocol.for.Genesis.platform.10.pdf)
[Smartgrid.pdf](https://github.com/klejejs/ha-thermia-heat-pump-integration/files/8592469/Smartgrid.pdf)
?

**Comment by klejejs** [comment]
@Mi3czy, unfortunately, the local connection is out of scope for this specific project as it specifically focuses on Thermia online API. Also, I do not have a local connection set up, so it would be technically impossible for me to test the functionality even if I chose to support it.
Home Assistant actually has its own [Modbus integration](https://www.home-assistant.io/integrations/modbus/), so you could check that one out, maybe it would fit your needs.

**Comment by Mi3czy** [comment]
Thanks for the reply, Ive used the modbus integration before but its not that handy :D thats why I'm looking for an alternative.
I saw there's another repo doing the local modbus thing: https://github.com/CJNE/thermiagenesis

It currently just has a unit issue for electric meter value's

**Comment by klejejs** [comment]
The core of the issue has been implemented, and the mentioned sensors have been in Home Assistant for some time, thus closing the issue.
