### ISSUE TITLE
Thermia status, Compressor, heating, hot water

### ISSUE THREAD

**Issue by zama737** [klejejs/ha-thermia-heat-pump-integration#29]
Thank you for such a great integration. 

Planning to automate heat pump according to the nordpool hour cost. To do that need to calculate integral, and to do that would need to know pump current status. 

Would be good to get following information from the app to be exposed to the home assistant:

Operational Status
Auxiliary heater:
3kW
6kW
9kW

Status:
Compressor status
Brinepump status
Hot water status
Heating status
Integral status

Thanks!

**Comment by klejejs** [comment]
The latest release has added these values.
