### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by kejXero** [klejejs/ha-thermia-heat-pump-integration#30]
Hello. I am new user with a new Caliba Duo just installed. I am able to login to thermia.com but i am not able to login to the integration using the same credentials. Any hints on getting a thermia username that is not an email.

**Comment by PalmSwe** [comment]
Same problem for me since 4 days ago. Can login to online.thermia.com but not in the integration, in HomeAssistant. Have had it working for more than 5 months untill this week.

**Comment by patrikrask** [comment]
Same for me
Thermia Calibra 7 Genesis
Working to login at thermia website but not in the python API or the HA integration

**Comment by klejejs** [comment]
Thanks for reporting the issue. It looks like Thermia has changed its authentication method.
Can you please confirm what API type are you using - `classic` or `genesis`?

**Comment by patrikrask** [comment]
genesis

Den ons 19 okt. 2022 kl 17:00 skrev Krisjanis Lejejs <
***@***.***>:

**Comment by Stefan71a** [comment]
A question, 
Have you received a question in your mobile app or on the home page about to transfer your account to a new solution?
I got this question about 2 weeks ago there I said yes to migrate me to the new system (I still have the old classic interface) and that data is still working after migration, but as I stated in previous answer you may face issue related to that Thermia is developing the Genesis integration to give it enhancements related to control of the heatpump. 

//Stefan

**Comment by patrikrask** [comment]
My father created the online account just some days ago

ons 19 okt. 2022 kl. 21:07 skrev Stefan71a ***@***.***>:

**Comment by klejejs** [comment]
Yes, Thermia has changed their login flow recently and that has broken login for some. I'll be looking into fixing that.

**Comment by Bumpeboy** [comment]
I also have the same problem.
Can't login via HA Integration, but works fine on the website.
I migrated to Thermia's new interface (did that before I found this Integration), but I use the Classic API.

**Comment by kejXero** [comment]
Looking forward for your update  😀 anything I can help with?

/Henrik

Med venlig hilsen

Henrik
________________________________

**Comment by klejejs** [comment]
The latest release, `2.11` should fix the issue as the underlying API login flow was updated. Please reopen the issue if any of you still encounter any problems.
