### ISSUE TITLE
Diplomat status monitoring

### ISSUE THREAD

**Issue by oulitja** [klejejs/ha-thermia-heat-pump-integration#44]
Thank you for this great integration; measurements and set temp works perfectly.

I'm not getting any changes on statuses on HA. On online thermia they do show correctly; (true or false). On HA they show constant values without changing according to actual pump states:
Compressor status; 1
Brinepump status; 2
Hot water status; 16
Heating status; 32

BR, Jari

**Comment by klejejs** [comment]
Hello! Thanks for the report. This functionality is not implemented in the UI yet as it was not requested before. I'll try to find time next week to add this.

**Comment by oulitja** [comment]
There's also an issue with EVU function (should be another topic?): When EVU terminals are jumped with 10k serial resistor, heat target temp will decrease according to specified preset value. There isn't any monitoring for this function (not in Thermia online and neither on HA integration. I can see the correct lowered heat target on pump's local display, but online presents the non decreased target temp which isn't correct. You can see (or guess) the EVU status from change on integral- and desired supply line  temperature.
Would it be possible to include into the integration:
-control and read the desired amount of target temp decrease which EVU activation will set?
-read the status of EVU; on or off?
-read the correct target temp with active EVU influence observed?

**Comment by Er-i-c** [comment]
> Thank you for this great integration; measurements and set temp works perfectly.
> 
> I'm not getting any changes on statuses on HA. On online thermia they do show correctly; (true or false). On HA they show constant values without changing according to actual pump states: Compressor status; 1 Brinepump status; 2 Hot water status; 16 Heating status; 32
> 
> BR, Jari

Mine shows status Unkown in HA:

![image](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/101553133/e6c981a9-7438-4db5-ac82-238880a0cedf)

Running the python example script I get:
Compressor status: 1
Brine pump status: 2
Radiator pump status: None
Cooling status: 8
Hot water status: 16
Heating status: 32
Integral: 0.0

**Comment by klejejs** [comment]
Hi! The statuses should show up correctly now with the latest release. Please check and report back if there are still issues.

**Comment by TonyLar** [comment]
Works great now! Thanks :-)

**Comment by Er-i-c** [comment]
Works for me too, thanks!
