### ISSUE TITLE
Thermia Online integration not working

### ISSUE THREAD

**Issue by AriRosti** [klejejs/ha-thermia-heat-pump-integration#52]
Hi,

Looks that latest HA core update (2013.5 and/or OS 10.1) has caused issues:

Logger entry:

Logger: ThermiaOnlineAPI.api.ThermiaAPI
Source: custom_components/thermia/__init__.py:94
Integration: Thermia Heat Pump (documentation, issues)
First occurred: 6. May 2023 klo 16.46.24 (5414 occurrences)
Last logged: 09.31.03

Error fetching device info. 500
Error in getting device's alarms. 500

**Comment by klejejs** [comment]
Hello! Sorry to hear about this, but it looks like a temporary issue from Thermia itself. I will release small integration changes soon and they should help a bit, but if this happens again, there is nothing I can do and the only suggestion is to reload the integration.
Sorry about this :(
