### ISSUE TITLE
Hot water temperature or tap water temperature

### ISSUE THREAD

**Issue by Garanzia2** [klejejs/ha-thermia-heat-pump-integration#54]
hi. 
Great integration. 
Is it possible to make hot water or tap water in such a way that you can change the operation type on the entity "hot_water_temperature"
So you can set the operation type for tap water to "Anti Legionella" or "Tapwater heating" or "idle"
![Skærmbillede 2023-08-09 213647](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/132225691/954474df-e3d2-44df-a7a3-f88310c472d1)

**Comment by klejejs** [comment]
I, unfortunately, have a different heat pump than you, so to help me figure this out, can you please follow [these instructions](https://github.com/klejejs/python-thermia-online-api#regarding-unsupported-models) and send me the debug file?

**Comment by klejejs** [comment]
This is stale as the integration has changed a lot since the issue was reported. Please open a new issue if there is still a problem.
