### ISSUE TITLE
Thermia Calibra Cool 7 BW heatpump with ha-thermia-heat-pump-integration

### ISSUE THREAD

**Issue by renaatdb** [klejejs/ha-thermia-heat-pump-integration#59]
Hi.
Thank you for such a great integration!
Now I can use the "Hot Water Boost" button when there is solar over-production current. I planned to use the Smart Grid - SG contacts from the Termia in the future, but now I can use this integration.
In the Thermia are 2 digital in (EVUSmart Grid 1 and Smart Grid 2).
Both open (0 and 0) give normal position.
0 and 1 = Comfort
1 and 1 = Boost ( I wonder if this is Hot Water Boost ?)

I have the Thermia Calibra Cool 7 BW pump.
Software versie
10.1.5

I'm using V3.1.2 release and core 2023.09.2
For the moment I have also No Operational status.
Regards
renaatdb

**Comment by klejejs** [comment]
I, unfortunately, have a different heat pump than you, so to help me figure this out, can you please follow [these instructions](https://github.com/klejejs/python-thermia-online-api#regarding-unsupported-models) and send me the debug file?

**Comment by renaatdb** [comment]
I feel stupid but I can't do it.
pip install -r requirements.txt give me ERROR: Could not open requirements file (Erro2) No such file ore directory: 'requirements.txt'

[How to use api:](https://github.com/klejejs/python-thermia-online-api#how-to-use-api)
See [example.py](https://github.com/klejejs/python-thermia-online-api/blob/main/example.py) file for examples.

To execute the example file, first run pip install -r requirements.txt to install the required dependencies, then run python3 example.py to execute the example file. You will be prompted to enter your username and password, and then the example file will run. If do not want to manually enter your credentials every time, you can edit the credentials.py file and add your credentials there.

**Comment by nanodreams** [comment]
Hi @renaatdb,

I'm also interested on this topic. I have the same heatpump Calibra 7 Cool. 
BTW: I also got solar panels ... but didn't see EVUSmart. Do you have any documentation comercial/technical how this works?

I have 3 different electricity ranges during the day .. and I would also like to have the "heatpump" only to heat water/house when the production of electricity from solar panels kick in. I show in the MODBUS documentation that there are "values" to limit the "max" gear of the heatpump for heating/water ... it would be cool to be able to "limit the heatpump" based on your "grid production". ;-)

PS: Waiting for my orange pi 5 plus ... to finally setup everything.

**Comment by renaatdb** [comment]
Hi@nanodreams.
Sorry in Dutch
https://www.geotherma.be/slimme-sturing-van-warmtepomp/
https://www.geotherma.be/wp-content/uploads/2021/10/Thermia-Modbus-protocol_compressed.pdf
https://tomclaus.be/home-automation/thermia-warmtepomp-uitlezen-en-sturen-via-modbus-en-loxone/
On the BM card you can find EVUSmart grid 1 en 2 contacts.
For the moment I use HA and thermia integration so I do Hot water boost whe sun is on my solar panels.

**Comment by nanodreams** [comment]
Hi @renaatdb  appreciated the links.

Since our Calibra 7 Cool has genesis online, I guess no need for MODBUS via RTU, so it will be easier via TCP.
Waiting for my hardware to get my hands "dirty", so I'll keep you updated. 

PS: Good to know someone with similar pump and need ;-)

**Comment by cmragnar** [comment]
> I feel stupid but I can't do it. pip install -r requirements.txt give me ERROR: Could not open requirements file (Erro2) No such file ore directory: 'requirements.txt'
> 
> [How to use api:](https://github.com/klejejs/python-thermia-online-api#how-to-use-api) See [example.py](https://github.com/klejejs/python-thermia-online-api/blob/main/example.py) file for examples.
> 
> To execute the example file, first run pip install -r requirements.txt to install the required dependencies, then run python3 example.py to execute the example file. You will be prompted to enter your username and password, and then the example file will run. If do not want to manually enter your credentials every time, you can edit the credentials.py file and add your credentials there.

has it resolved or still the same problem?

**Comment by klejejs** [comment]
Hey! This has been here for too long but, unfortunately, I had no way to debug and solve the issue before. In case you still want a feature to be implemented, please create a new issue and add the relevant data there, so I can investigate adding the needed sensor/switch. The debug process has now been made much easier with the latest integration release and it should help me solve problems easier and quicker.
