### ISSUE TITLE
Add the outdoor temperature

### ISSUE THREAD

**Issue by air2** [klejejs/ha-thermia-heat-pump-integration#6]
Hello Krisjanis,

First of all happy new year :).

I added the outdoor temperature sensor in my fork. But I never ever programmed phyton before, and I do not have any HA programming experience, so I guess I did not a very good job, but it works. (thanks to all your hard work!) anyway, if you want to add it the way I did it, I could create a pull request, else I just wait for your implementation and use my own repo for now.

Thanks again for fixing the stuff for the iTec heat pump. It works like a charm in HA for now.

**Comment by klejejs** [comment]
Hi,

I am glad to hear that! I actually looked into it too and was successful. With HA and Python, there are some practices to consider and as I haven't had too much experience in Python either, it was a bit tedious, but I think I have refactored the component. There is a small bug with initialization in my local branch that I haven't yet fixed, as soon as I do, I will release an update.

Happy to hear that the heat pump works! And happy new year to you too 😉 

P.S. I'll leave the ticket open until the new version is out.

**Comment by klejejs** [comment]
Had some time and fixed the issues. V2 has been released and outdoor temperature sensor is available now as an entity. You will have to, unfortunately, re-add your heat pump as I decided not to support `configuration.yaml`.
You will have to remove data from the file and search for integration through the Integrations page.

**Comment by air2** [comment]
Thank u for the updates!! And readding should not be a problem. I use the community extension to find your integration and can find the V2 version indeed. But I do not know how to enter a username and password without the configuration.yaml? Also the readme.md still states I have to use the configuration.yaml. So I think I misunderstand something?

**Comment by air2** [comment]
Hmm it was showing your repo, but downloaded my repo, because that was still added as custom integration. So I think that was why I was seeing an old  readme file. I do not understand how it could show version 2 though. Anyway I think I misconfigured it :S

**Comment by air2** [comment]
After some fiddling with HACS and HA I got it working. Good you got rid of the configuration.yaml. Much better this way!. Would be great if you could move it someday to HA itself instead of HACS. Anyway thank u for the great work!!
