### ISSUE TITLE
Operational Status showing periodic unknown

### ISSUE THREAD

**Issue by oskari** [klejejs/ha-thermia-heat-pump-integration#62]
Model: Thermia iTec

I don't think my operational status has worked before, but after upgrading today to 3.2.0 it started showing something, but seems that not all statuses are shown:
![kmzjyCs](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/506596/c70d607e-8013-4d9f-9d66-574fd3b00f28)

I've attached a debug file if it's any help
[debug-16102023.txt](https://github.com/klejejs/ha-thermia-heat-pump-integration/files/12920922/debug-16102023.txt)

**Comment by fredrikostlind** [comment]
I have the same problem with my integration to a Thermia Diplomat Duo.

The following sensors is usually showing "unknown" status when in operation:
- Brine Pump Status
- Compressor Status
- Heating Status
- Hot Water Status
- Operational Status

![Screenshot 2023-11-28 at 09 28 35](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/82604803/05b20ca6-e316-4b5e-bc88-69fa314b7163)
![Photo Nov 28 Screenshot](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/82604803/946e9222-d9dd-46d3-acbc-b2b1d664a357)

But then operation is completed, the status changes to "clear".
![Screenshot 2023-11-28 at 10 07 20](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/82604803/51070e18-82cb-4a81-84b5-db79261a2f98)

Debug log is only showing "DEBUG (MainThread) [custom_components.thermia] Finished fetching thermia data in 0.586 seconds (success: True)"

**Comment by klejejs** [comment]
The operational status entity was removed with the latest release as it did not make sense and sensors were fixed not to show "unknown". Please update the integration, check, and report back if there are still issues.
