### ISSUE TITLE
Can't  change temperature?

### ISSUE THREAD

**Issue by kleijnweb** [klejejs/ha-thermia-heat-pump-integration#63]
First off all thank you for this, it seems to work fine. However the number of  control options is very limited. The one thing I'm missing is being able to set the global temperature target. Is  that not supported by the API or something that could be added?

**Comment by kejXero** [comment]
The climate entity disappeared after update to HA 2023.11.

**Comment by klejejs** [comment]
Hey! This has been here for too long but, unfortunately, I had no way to debug and solve the issue before. In case you still want a feature to be implemented, please create a new issue and add the relevant data there, so I can investigate adding the needed sensor/switch. The debug process has now been made much easier with the latest integration release and it should help me solve problems easier and quicker.
