### ISSUE TITLE
Invalid config HA 2023.11 - unable to prepare setup for platform thermiagenesis.climate

### ISSUE THREAD

**Issue by kejXero** [klejejs/ha-thermia-heat-pump-integration#64]
Wrong integration, this was targeted the [thermiagenesis](https://github.com/CJNE/thermiagenesis) integration. i will close this issue.

Thank you for your great work on this integration. My issue started when I updated my Home assistant to HA2023.11. After this update the climate.heat entity disappeared and the possibility to set the heat target also disappeared. 

I tried without success, a reinstall if your integration, with a subsequently re-activation of used entities. Some "feed back info" changed from ON to PLUGGED IN.

Log copy from HA:
Unable to prepare setup for platform thermiagenesis.climate: Platform not found (No module named 'homeassistant.util.temperature').
November 20, 2023 at 21:32:51 – (ERROR) setup.py

Googling tells me that that that module was deprecated a year ago, so I’m guessing it was finally removed in 2023.11.

My Thermia as an Thermia Calibra 12

**Comment by a94roipe** [comment]
I have exactly the same issue.
