### ISSUE TITLE
Missing entities after HA 2024.1.0 upgrade

### ISSUE THREAD

**Issue by PalmSwe** [klejejs/ha-thermia-heat-pump-integration#65]
Hi,

Missing entities like main heater. After upgrading to latest HA, about half of Thermia classic entities are missing like the heater for viewing or changing temperature.
Half of the entites as for example water heater is still there but the most important one (for me) are gone.

I have tried restaring HA and removing the integration and adding it again but without any success. Any suggestion on what to do or is it a bug in the newest HA version?

Seems like when I go to Thermia online "https://online.thermia.se", then I can see and change things like temperature so no problem with their web.

Thanks in advance.

**Comment by klejejs** [comment]
I see the issue, looks like the HA integration API has changed with this release. I will try to fix it during the weekend at the latest.

**Comment by robertmosen** [comment]
Hi,

I experiance tge exact same behaviour.

kindly,
Robert

**Comment by PalmSwe** [comment]
Looks like everything is working again with version 2024.1.1.

**Comment by klejejs** [comment]
Yeah, looks like they deprecated some features but it also broke stuff. In any case, I will move away from deprecations to prevent issues in the future.

**Comment by robertmosen** [comment]
It works now.
