### ISSUE TITLE
Great work! Features suggested

### ISSUE THREAD

**Issue by bartoszzurawiecki** [klejejs/ha-thermia-heat-pump-integration#7]
Hello Krisjanis, you're doing amazing work. I thought my heat pump will never work with HA, but now it does thanks to you.

If I could ask you for adding few features, it would be very nice to have them:
1. Hot water control (on bottom left of "Device operation details" page - just On/Off would be great)
2. active alarms information (at least that there is any active alarm)

of course any other feature will be greatly appreciated.

P.S. I use Danfoss DHP-AQ heat pump (Thermia Atec) and it works with your integration/python module, even if my module shows my pump as iTec (on Thermia Online and in your integration).

Thanks again for your great work!

**Comment by air2** [comment]
The alarm sounds like a great idea for me too. 
also for me the hot water is just on/off but I assume that is not the state for all heat pumps?? In the normal interface I can only switch between:
OFF and Compressor
So I guess the interface somehow knows the possible states?

**Comment by klejejs** [comment]
Thanks for your requests!]

I will look into adding alarms to Home Assistant, I agree they might be very useful.

As for hot water control, I will have to look into how I can add it because my heat pump does not have that functionality separately. @bartoszzurawiecki Could you please add a screenshot of how it looks?
My heat pump controls look the same as when logging in with Thermia demo account (`demo:demo`), maybe, if you have time, you can check that account out and mention the differences?

**Comment by bartoszzurawiecki** [comment]
![image](https://user-images.githubusercontent.com/68705797/149242780-381f1fe5-6156-40dd-88da-db0cc157ea33.png)

on the details page I have something more on the bottom - controlling Hot water would allow me to heat water only when I produce energy on my roof

**Comment by klejejs** [comment]
I have released a new version that includes a hot water switch for supported heat pumps and an active alarm count sensor.
Feel free to update, test the integration and leave any comments if necessary. Otherwise, I guess this could be closed.

**Comment by air2** [comment]
I can confirm I see the alarm sensor and it shows my current alarm state.
Also I do not see the hot water switch, which I do not have, so that works fine for me too.
Great work!!!!

**Comment by bartoszzurawiecki** [comment]
Thank you @klejejs for your work!

**Comment by bartoszzurawiecki** [comment]
Both features suggestions are meet, thank you
