### ISSUE TITLE
Calibra 12 - Temperature shows unknown

### ISSUE THREAD

**Issue by jgaurilo** [klejejs/ha-thermia-heat-pump-integration#73]
Hi,

I have Thermia Calibra 12 heat pump. Temperature shows unknown in home assistant ui.

HA version: 2023.11.3
HAOS: 11.1
Thermia Heat Pump Integration: 3.3.1

![image](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/25196459/e68d83a4-8ab8-4c77-a9e7-b6404d12930e)
![image](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/25196459/2b45671a-58a7-43e5-8758-29eecffbd84c)

Debug log: 
[debug.txt](https://github.com/klejejs/ha-thermia-heat-pump-integration/files/13956498/debug.txt)

**Comment by eljobo** [comment]
+1 for Thermia Diplomat

**Comment by effinamon** [comment]
Thermia Online was down for maintenance yesterday (2024-01-16) from 12:00-20:00 so it may be due to changes they made. My heatpump devices are now duplicated with an empty (old id) one and a new one (new id). No issues though.

**Comment by eljobo** [comment]
> Thermia Online was down for maintenance yesterday (2024-01-16) from 12:00-20:00 so it may be due to changes they made. My heatpump devices are now duplicated with an empty (old id) one and a new one (new id). No issues though.

Yeah, reloading the integration got it working again.

**Comment by jgaurilo** [comment]
Behavior was same before the update of the integration and changes that Thermia made. Genesis api was replaced with classic.

**Comment by pumpan** [comment]
this is still an issue.

**Comment by Tobbe7612** [comment]
Still an issue for me to..

**Comment by klejejs** [comment]
Can you please confirm you are not allowed to change operation, i.e., heating, auto, etc. through UI?

**Comment by Tobbe7612** [comment]
For me it is still the same, can not select mode ( or "Läge" in Swedish 😊)

**Comment by klejejs** [comment]
I have just released version 4.2.0 that should fix the issue by disabling the operation mode feature if operation change is not allowed. Please check and report back if it is working now.

**Comment by Tobbe7612** [comment]
The selection box is now gone.
Still a unknown(Okänd) status showing, se pictures![image](https://github.com/user-attachments/assets/4093956c-ed11-4459-8fb9-7b66a66dd25f)![image](https://github.com/user-attachments/assets/4d135b21-9b75-4f16-be39-cb927411ccb2)

**Comment by klejejs** [comment]
@Tobbe7612 can you please show how the current state for water_heater entity looks for you in developer tools?

**Comment by Tobbe7612** [comment]
![image](https://github.com/user-attachments/assets/1d8e9074-c79b-473c-8c2f-024edd1ec4b5)

**Comment by Tobbe7612** [comment]
I hope this is what you wanted...

**Comment by klejejs** [comment]
Hey! I just released version `5.1.0`, could you please update the integration and check if the issue is still present?

**Comment by pumpan** [comment]
Works great! 😃

**Comment by klejejs** [comment]
Looks like this is fixed. If the problem still persists, please open a new issue.
