### ISSUE TITLE
Thermia changed their domain / URL-link 

### ISSUE THREAD

**Issue by hutasje** [klejejs/ha-thermia-heat-pump-integration#74]
Hi there, 

Maybe you're already aware, 

I noticed that since a day or so HA wasn't showing updates any longer. 
It seems that Thermia have altered their domain.

old: 
https://www.online-genesis.thermia.se/

new: 
https://online.thermia.se/

![image](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/74378801/a14ddb6e-3ee6-4baf-97ec-8b1bc5538402)

Kind regards, 
Vernon

**Comment by qvarting** [comment]
Yea, you need to change from `genesis` to `online`. 

```
Depending on the url you use to see your heat pump online, you need to choose the following API type:
classic - for url: https://online.thermia.se/
genesis - for url: https://online-genesis.thermia.se/
```

Remove the integration and add it again and choose classic this time.
Cheers

**Comment by hutasje** [comment]
You are a diamond ! Thank you for the hint ! 

(ps. Very appreciative for this integration... pls don't  stop supporting 😀)
