### ISSUE TITLE
Integration not working as off 26.3.2024

### ISSUE THREAD

**Issue by MusicmanP3** [klejejs/ha-thermia-heat-pump-integration#75]
The integration stopped working yesterday (26.3) afternoon. 
When trying to reload it initializing for a long time and then "Failed to set up" appears. 
Has Thermia done some changes to their servers?  
I can however log in to https://www.online.thermia.se/ and everything seems fine.
I´m running the latest release V3.3.1 and Home Assistant is updated as well.

**Comment by Nilledog** [comment]
Mine is working now after relood.

**Comment by MusicmanP3** [comment]
Yes! So is mine! All sorted out!
