### ISSUE TITLE
Integration seems broken (Thermia Atlas 18) 

### ISSUE THREAD

**Issue by ackjewtn** [klejejs/ha-thermia-heat-pump-integration#76]
I recently started to get errors from the integration, but i've lost the logs containing the error after i removed configuration to test.

It was a JSON decode error, suggesting that the response from the API was something else (probably some error). 

Now I'm trying to set up the integration again, and getting `Credentials are invalid.` in the config flow. The logs are saying the following: 
```
2024-04-30 15:53:43.225 ERROR (MainThread) [custom_components.thermia.config_flow] Expecting value: line 1 column 1 (char 0)
```

The Thermia Web App is operational and i'm able to log in there.

**Comment by Nilledog** [comment]
Same situation here, I Can see the Thermia  app (Android) is changed, now you have to confirm when you change operation mode.

**Comment by OldSmurf56** [comment]
Hi
I seem to be in the same boat. After a reboot of HA, I am not receiving data from Thermia (I have a Diplomat G3). Trying to reload the integration and set up a new instance returns this error :
Log details (ERROR)
This error originated from a custom integration.
Logger: custom_components.thermia.config_flow
Source: custom_components/thermia/config_flow.py:52
integration: Thermia Heat Pump ([documentation](https://github.com/klejejs/ha-thermia-heat-pump-integration), [issues](https://github.com/klejejs/ha-thermia-heat-pump-integration/issues))
First occurred: 20:05:00 (4 occurrences)
Last logged: 20:07:12

.. .and I am able to log in through the Thermia app as well as through web interface.
Expecting value: line 1 column 1 (char 0)

**Comment by klejejs** [comment]
Thank you all for reporting! Please update to the latest 3.4.0 version to fix the issue.

**Comment by Sepulnation** [comment]
You're best. Thank you for your quick reaction!
