### ISSUE TITLE
Looks like Thermia portal is down 

### ISSUE THREAD

**Issue by fclauson** [klejejs/ha-thermia-heat-pump-integration#86]
You can login in but there is no data from some time over night

**Comment by klejejs** [comment]
This is a 3rd party integration that is connecting to Thermia for information but is in no way directly related to the company or the processes it is running. Thus, there is nothing that can be done relating to the portal problem, it is not the problem of the integration and the only thing we can do is to wait, see if Thermia fixes it and whether it will have an impact on this integration afterwards. But until then, there is, unfortunately, there is nothing to do.
