### ISSUE TITLE
add back running_operational_statuses?

### ISSUE THREAD

**Issue by hjort1** [klejejs/ha-thermia-heat-pump-integration#89]
Model: Thermia Atlas 12

'Running operational status' was removed some releases ago, but it still exists in the API.

After every time I upgrade this integration I add back this code to sensor.py under the comment "# Operational status data" (currently row 259).

```
        if heat_pump.running_operational_statuses is not None:
            hass_thermia_sensors.append(
                ThermiaGenericSensor(
                    coordinator,
                    idx,
                    "is_online",
                    "Operational Status",
                    "mdi:thermostat",
                    EntityCategory.DIAGNOSTIC,
                    None,
                    None,
                    "running_operational_statuses",
                    None,
                )
            )
```

This will create a sensor called sensor.xxx_operational_status and the idle state is ['STATUS_NO_DEMAND']. 
(It can for sure be made more pretty)

Could you please add it back or have an option to include it? 
I could try to add an PR but I am not confident enough to know that I won't mess up anything else.

**Comment by Tobbe7612** [comment]
I have a Thermia Calibra and I also miss the operational status information, that would be very helpful

**Comment by klejejs** [comment]
The latest release `5.0.0` refactors how operational statuses are shown in Home Assistant, so you should now see all operational statuses your heat pump provides. Please check it out and let me know if it is working as expected. Also, please keep in mind that this release has some breaking changes and read about them in the release notes.

**Comment by hjort1** [comment]
Very nice! Thank you very much. Closing the issue.
