### ISSUE TITLE
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'model_id'

### ISSUE THREAD

**Issue by dim123dim123** [klejejs/ha-thermia-heat-pump-integration#93]
HA -2024.5.5
Any ideas?

home-assistant   | 2024-10-06 07:11:57.257 ERROR (MainThread) [homeassistant.components.switch] Error adding entity None for domain switch with platform thermia
home-assistant   | Traceback (most recent call last):
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
home-assistant   |     await coro
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 750, in _async_add_entity
home-assistant   |     device = dev_reg.async_get(self.hass).async_get_or_create(
home-assistant   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant   | TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'model_id'

**Comment by klejejs** [comment]
Hi! Since the release `4.1.0`, HA version `2024.8.0` or higher is required for the integration to work.
