### ISSUE TITLE
Hot Water Operational Status not working

### ISSUE THREAD

**Issue by janfryauf** [klejejs/ha-thermia-heat-pump-integration#96]
Hello,

I was using this integration for some time without any problems, but it seems after the latest update status for Hot Water  "Hot Water Operational Status" is not working anymore.

My model is: iTec

<img width="1406" alt="image" src="https://github.com/user-attachments/assets/c3ea3a0b-5c14-4d69-b661-45c89fc548d6">

Debug file:
[debug.txt](https://github.com/user-attachments/files/17351006/debug.txt)

I'm happy to help in any way.

**Comment by OldSmurf56** [comment]
Same issue here ... and also missing brine pump status, compressor status,
heating status. and the two 3kW and 6kW aux heater status.
Apart from that - I love this integration which has enabled me to be in
total control of my Thermia including initiating EVU stop between 17:00 and
21:00 hrs.

Den lør. 12. okt. 2024 kl. 20.17 skrev janfryauf ***@***.***>:

**Comment by klejejs** [comment]
Hey! Thanks for reporting the issue. With the latest release the integration code was refactored a bit, so some entities did disappear and that was expected. New entities were added to replace the ones that had disappeared (see release notes).
@janfryauf what was the value you saw for the hot water previously, and how do you see it on the Thermia Online site? According to your `debug.txt` file, hot water for your heat pump is disabled/hidden.

**Comment by janfryauf** [comment]
Hi, thanks for pointing me to the right direction, I figured what's wrong. I have automation controlling Hot water switch, and when the switch if OFF, then the status is disabled/hidden. If I put it to ON it's still not visible because HA doesn't reload the "connection". I guess I will just stop using this status information.

**Comment by klejejs** [comment]
@janfryauf are you saying that when you turn the switch on and reload the integration, you are able to see the status? If so, sounds like a bug to me. Could you please send me the debug file you generate while the hot water switch is on?

**Comment by janfryauf** [comment]
[debug.txt](https://github.com/user-attachments/files/17374875/debug.txt)

**Comment by klejejs** [comment]
Hey! I just released version `5.1.0`, could you please update the integration and check if the issue is still present?

**Comment by janfryauf** [comment]
I can confirm it's working. Thanks a lot!
